#!/usr/bin/env python3
"""
update_context.py — post-commit hook for clevertech context maintenance.

Runs automatically after every git commit.  It:
  1. Reads the just-committed diff (staged files only).
  2. Looks up each changed file in routes.yaml to find the relevant topic(s).
  3. Appends a timestamped changelog entry to implementation_status.md so the
     context stays in sync with the code without manual editing.

Install (one-time):
    cp context/update_context.py .git/hooks/post-commit
    chmod +x .git/hooks/post-commit

Bypass for a single commit:
    GIT_SKIP_CONTEXT_UPDATE=1 git commit …
"""

import os
import sys
import subprocess
import yaml
from datetime import datetime, timezone

# ── paths ─────────────────────────────────────────────────────────────────────
REPO_ROOT = subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True
).strip()

# The app lives one level inside the repo  (apps/clevertech/)
# Adjust APP_REL if your layout differs.
APP_REL = "clevertech"
APP_ROOT = os.path.join(REPO_ROOT, APP_REL)
CONTEXT_DIR = os.path.join(APP_ROOT, "context")
ROUTES_FILE = os.path.join(CONTEXT_DIR, "routes.yaml")
IMPL_STATUS = os.path.join(CONTEXT_DIR, "implementation_status.md")


def load_routes():
    """Return routes dict: source-path → [topic-files]."""
    if not os.path.exists(ROUTES_FILE):
        return {}
    with open(ROUTES_FILE) as f:
        return yaml.safe_load(f) or {}


def get_committed_files():
    """Return list of files that were in the last commit."""
    out = subprocess.check_output(
        ["git", "diff-tree", "--no-commit-id", "-r", "--name-only", "HEAD"],
        text=True,
    )
    return [f.strip() for f in out.splitlines() if f.strip()]


def get_commit_message():
    """Return the commit message of HEAD."""
    return subprocess.check_output(
        ["git", "log", "-1", "--format=%s"], text=True
    ).strip()


def get_commit_hash():
    """Short hash of HEAD."""
    return subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"], text=True
    ).strip()


def match_routes(committed_files, routes):
    """
    For each committed file, check if any key in routes is a suffix match.
    Returns dict: topic_file → set of matched source files.
    """
    hits = {}                          # topic → [source_files]
    for src_path in committed_files:
        for route_key, topics in routes.items():
            # route_key is relative to APP_ROOT; src_path may be relative to
            # REPO_ROOT or APP_ROOT depending on git layout — do suffix match.
            if src_path.endswith(route_key) or route_key.endswith(src_path):
                for t in topics:
                    hits.setdefault(t, []).append(src_path)
    return hits


def append_changelog(hits, commit_msg, commit_hash):
    """Append a changelog block to implementation_status.md."""
    if not os.path.exists(IMPL_STATUS):
        print("[update_context] implementation_status.md not found — skipping changelog.")
        return

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "",
        "---",
        "",
        f"### Auto-changelog [{now}] — `{commit_hash}`",
        "",
        f"**Commit:** {commit_msg}",
        "",
        "**Files changed and their context topics:**",
        "",
    ]

    for topic, sources in sorted(hits.items()):
        lines.append(f"- **{topic}**")
        for s in sorted(set(sources)):
            lines.append(f"  - `{s}`")

    lines.append("")
    lines.append(
        "> *This entry was auto-generated by `context/update_context.py`.  "
        "Update the relevant topic file if design decisions changed.*"
    )
    lines.append("")

    with open(IMPL_STATUS, "a") as f:
        f.write("\n".join(lines))

    # Stage the updated file so it shows up in `git status` for next commit
    subprocess.run(
        ["git", "add", IMPL_STATUS],
        cwd=REPO_ROOT,
        capture_output=True,
    )
    print(f"[update_context] appended changelog to implementation_status.md ({len(hits)} topic(s) affected)")


def main():
    # honour skip flag
    if os.environ.get("GIT_SKIP_CONTEXT_UPDATE"):
        return

    routes = load_routes()
    if not routes:
        # routes.yaml missing or empty — nothing to do
        return

    committed = get_committed_files()
    if not committed:
        return

    hits = match_routes(committed, routes)
    if not hits:
        # No committed file matched any route — silent exit
        return

    commit_msg = get_commit_message()
    commit_hash = get_commit_hash()
    append_changelog(hits, commit_msg, commit_hash)


if __name__ == "__main__":
    main()
